#!/bin/bash
# Wrapper around pkg-config that perfers the platform's install root before the system's
# installed packages.
#
# Meant to be invoked from the root of the repo (next to libraries/)
#
PKG_CONFIG_PATH=./libraries/install-root-${PLATFORM}/lib/pkgconfig pkg-config "$@"
